import streamlit as st
from streamlit_gsheets import GSheetsConnection
import pandas as pd
from datetime import datetime

# Set page configuration
st.set_page_config(page_title="Karibu Task Manager", layout="wide")

# 1. Complete Category & Subcategory System (Updated from Map Files)
CATEGORIES = {
    'PVC': ['CLEAR', 'PRC', 'UV', 'UVPC', 'CUT', 'PLN', 'GLDC', 'GLDP', 'ECO', 'CLRPRC', 'FRPL', 'FRCUT', 'FRPRC', 'MAG', 'RFL', 'HNY', 'UV CLEAR STICKER'],
    'EMB': ['STD', 'PRM'],
    'CAN': ['COT', 'UV', 'ECO', 'OTH'],
    'BAN': ['UV', 'ECO', 'TD', 'FECO', 'FUV', 'POP', 'STD', 'PRM', 'TELSCP', 'BKLUV', 'BACKLIGHT'],
    'MAP': ['NRM', 'PP', 'POP'],
    'SUB': ['SUB'],
    'DTF': ['DTF'],
    'CON': ['UV', 'ECO', 'PLN'],
    'FLT': ['UVD', 'PEN', 'NOTE', 'ACR'],
    'PUB': ['FLY', 'BR', 'BC', 'OTH'],
    'CUS': ['CUS', 'NFC-CRD']
}

# 2. Establish Connection
conn = st.connection("gsheets", type=GSheetsConnection)

# 3. Pull URL from Secrets
try:
    SHEET_URL = st.secrets["connections"]["gsheets"]["spreadsheet_url"]
except Exception:
    st.error("Missing 'spreadsheet_url' in Streamlit Secrets!")
    st.stop()

def load_wo_data():
    """Load WO data and clean columns/numbers"""
    try:
        data = conn.read(spreadsheet=SHEET_URL, worksheet="WO_Log", ttl=0)
        data.columns = [str(c).strip() for c in data.columns]
        
        if 'WO Number' in data.columns:
            # Clean WO Number for searching (string, uppercase, no .0)
            data['WO Number'] = (
                data['WO Number']
                .astype(str)
                .str.replace(r'\.0$', '', regex=True)
                .str.strip()
                .str.upper()
            )
        return data
    except Exception as e:
        st.error(f"Error loading WO_Log: {e}")
        return pd.DataFrame()

def load_user_list():
    """Load names from 'users' tab, Column B ('Name')"""
    try:
        user_data = conn.read(spreadsheet=SHEET_URL, worksheet="users", ttl=0)
        user_data.columns = [str(c).strip().lower() for c in user_data.columns]
        
        if 'name' in user_data.columns:
            name_list = user_data['name'].dropna().astype(str).str.strip().unique().tolist()
            return [n for n in name_list if n != ""]
        return []
    except Exception:
        return []

st.title("📋 Karibu Work Order Manager")

try:
    # Initial Data Load
    df = load_wo_data()
    staff_names = load_user_list()

    # --- SECTION 1: ADD NEW WORK ORDER ---
    with st.expander("➕ Create New Work Order", expanded=False):
        with st.form("new_wo_form", clear_on_submit=True):
            col1, col2 = st.columns(2)
            f_client = col1.text_input("Client Name").strip()
            f_phone = col2.text_input("Phone Number").strip()
            
            # Category & Subcategory Dropdowns
            col3, col4, col5 = st.columns(3)
            f_cat = col3.selectbox("Category", options=[""] + sorted(list(CATEGORIES.keys())))
            
            # Dynamic Subcategory update
            sub_options = CATEGORIES.get(f_cat, []) if f_cat else []
            f_sub = col4.selectbox("Subcategory", options=sub_options)
            
            f_ver = col5.text_input("Version", value="V0")
            f_desc = st.text_area("Description").strip()
            
            if st.form_submit_button("Generate & Save Work Order"):
                if f_client and f_cat and f_sub:
                    # Logic to find the next WO Number (Autogenerated)
                    try:
                        # Convert column to numeric to find true max
                        nums = pd.to_numeric(df['WO Number'], errors='coerce')
                        last_wo = nums.max()
                        new_wo_num = int(last_wo) + 1 if not pd.isna(last_wo) else 1001 # Start at 1001 if empty
                    except:
                        new_wo_num = 1001
                    
                    # Date Logic (matches your script)
                    now = datetime.now()
                    iso_date = now.strftime("%Y-%m-%d")
                    short_date = now.strftime("%d%m%y")
                    
                    # Filename Format: WO[Num]_[Date]_[Cat]-[Sub]_[Client]_[Desc]_[Ver]
                    filename = (
                        f"WO{str(new_wo_num).zfill(3)}_{short_date}_"
                        f"{f_cat}-{f_sub}_{f_client}_{f_desc}_{f_ver}"
                    ).upper().replace(" ", "_")
                    
                    # Create New Entry
                    new_row = pd.DataFrame([{
                        "WO Number": str(new_wo_num),
                        "Date": iso_date,
                        "Category": f_cat,
                        "Subcategory": f_sub,
                        "Client_Name_Display": f_client.upper(),
                        "Client Phone": f_phone,
                        "Description": f_desc.upper(),
                        "Version": f_ver.upper(),
                        "Filename": filename,
                        "Timestamp": now.strftime("%Y-%m-%d %H:%M:%S"),
                        "Status": "Pending",
                        "Assigned To": "Unassigned"
                    }])
                    
                    # Append to local and Push to Sheet
                    updated_df = pd.concat([df, new_row], ignore_index=True)
                    conn.update(spreadsheet=SHEET_URL, worksheet="WO_Log", data=updated_df)
                    
                    st.success(f"Work Order #{new_wo_num} Created! Filename: {filename}")
                    st.rerun()
                else:
                    st.error("Missing required fields: Client, Category, and Subcategory.")

    # --- SECTION 2: SEARCH & EDIT ---
    st.subheader("🔍 Search & Update")
    search_query = st.text_input("Search by WO Number").strip().upper()

    if search_query:
        match = df[df['WO Number'] == search_query]
        if not match.empty:
            row = match.iloc[0]
            idx = match.index[0]
            with st.container(border=True):
                st.write(f"### Editing WO #{search_query}")
                st.caption(f"**Filename:** {row.get('Filename', 'N/A')}")
                
                edit_col1, edit_col2 = st.columns(2)
                
                # Status Dropdown (Case-blind match)
                status_list = ["Pending", "In progress", "Completed", "On Hold", "Cancelled"]
                curr_s = str(row['Status']).strip()
                try:
                    s_idx = [s.lower() for s in status_list].index(curr_s.lower())
                except:
                    s_idx = 0
                new_status = edit_col1.selectbox("Current Status", status_list, index=s_idx)

                # Assigned To Dropdown (from 'users' sheet)
                drop_opts = sorted(list(set(["Admin", "Unassigned"] + staff_names)))
                curr_a = str(row['Assigned To']).strip()
                if curr_a not in drop_opts and curr_a.lower() != 'nan' and curr_a != "":
                    drop_opts.append(curr_a)
                try:
                    a_idx = drop_opts.index(curr_a)
                except:
                    a_idx = 0
                new_assignee = edit_col2.selectbox("Assigned To", drop_opts, index=a_idx)

                if st.button("Save Changes ✅", use_container_width=True, type="primary"):
                    df.at[idx, 'Status'] = new_status
                    df.at[idx, 'Assigned To'] = new_assignee
                    conn.update(spreadsheet=SHEET_URL, worksheet="WO_Log", data=df)
                    st.success(f"WO #{search_query} successfully updated!")
                    st.rerun()
        else:
            st.error(f"Work Order '{search_query}' not found.")

    # --- SECTION 3: ACTIVE TASKS TABLE ---
    st.divider()
    st.subheader("🚀 Active Tasks")
    
    # Force columns to string for comparison
    df['Status'] = df['Status'].astype(str)
    df['Assigned To'] = df['Assigned To'].astype(str)

    # Filter logic: Pending, In progress, or Unassigned
    is_active_status = df['Status'].str.lower().isin(['pending', 'in progress'])
    is_unassigned = (
        (df['Assigned To'].str.lower().isin(['nan', 'unassigned', ''])) |
        (df['Assigned To'].isna())
    )
    
    # Filter the view
    active_df = df[is_active_status | is_unassigned]
    # Final exclusion of closed states
    final_view = active_df[~active_df['Status'].str.lower().isin(['completed', 'cancelled'])]

    if not final_view.empty:
        st.dataframe(
            final_view[['WO Number', 'Date', 'Client_Name_Display', 'Status', 'Assigned To']], 
            use_container_width=True, 
            hide_index=True
        )
    else:
        st.info("No active tasks found.")

except Exception as e:
    st.error(f"Application Error: {e}")
